import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import AppShell from "@/common/layout/AppShell";
import ScrollProvider from "./providers/ScrollProvider";
import { Toaster } from "react-hot-toast";
import AppBootstrap from "@/common/refreshToken-store/AppBootstrap";
import ReactQueryProvider from "./providers/react_tan_stack_quary/ReactQueryProvider";

const outfit = Outfit({
  variable: "--font-outfit",
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
          <ReactQueryProvider>
        <ScrollProvider>
          {" "}
              <AppBootstrap>
          <AppShell>{children}</AppShell>{" "}
          </AppBootstrap>
        </ScrollProvider>
          </ReactQueryProvider>
         <Toaster 
          position="top-right" 
          toastOptions={{
            style: {
              borderRadius: '10px',
              background: '#fff',
              color: '#333',
              boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
            },
            success: { duration: 3000 },
          }}
        />
      </body>
    </html>
  );
}
